### ISSUE TITLE
hashtags vs mentions

### ISSUE THREAD

**Issue by AlexECP** [StevenDevooght/tinyMCE-mention#38]
Hi,

is there a way to set it so a different list is displayed when the user types '#' then when they type '@'?

**Comment by StevenDevooght** [comment]
Hi,

It is possible to configure an [array](https://github.com/CogniStreamer/tinyMCE-mention#array-1) of delimiters.

The source setting can be configured as a [function](https://github.com/CogniStreamer/tinyMCE-mention#function) where you can differentiate between the configured delimiters.

**Comment by AlexECP** [comment]
awesome, thank you. not sure how I missed that in the readme.
