### ISSUE TITLE
Failed to load: ../mention/editor_plugin.js

### ISSUE THREAD

**Issue by ofcapl** [StevenDevooght/tinyMCE-mention#39]
Hi,
I've tried to setup mention plugin with my TinyMCE which I have in my Django app but I'm getting an error:

`Failed to load: localhost:8000/.../mention/editor_plugin.js`

I've copied whole repo to my TinyMCE's plugins directory (is it correct way? (I don't want to use bower etc.)) and there is not any file with name `editor_plugin.js`.

Please help.

**Comment by StevenDevooght** [comment]
You can find the `editor_plugin` javascript on the [3.5 branch](https://github.com/StevenDevooght/tinyMCE-mention/tree/3.5/mention). Note if you're using TinyMCE 4+ you have to use `plugin.js` from the master branch.

**Comment by ofcapl** [comment]
that worked, thanks!
