### ISSUE TITLE
Problem using function example

### ISSUE THREAD

**Issue by CMTietgen** [StevenDevooght/tinyMCE-mention#40]
I tried out your extension and it works well if I hard-code the source like in your example. However, if I try to use your function example (by copy/pasting it), the list never populates and closed almost as soon as it opens.

When I debugged it I got the error shown in the screenshot.

![mentions-error](https://cloud.githubusercontent.com/assets/13341574/15611810/121876a4-23fa-11e6-98b9-685a11ad4ae6.jpg)

Also, I am not sure how my JSON file should be formatted. It looks like the following:

![mentions-json](https://cloud.githubusercontent.com/assets/13341574/15611853/461dbbb2-23fa-11e6-9072-e796df70e70e.jpg)

Any thoughts on what I'm doing wrong and how to fix it?

- Chris

**Comment by CMTietgen** [comment]
I got it figured out. :)

**Comment by StevenDevooght** [comment]
+1
