### ISSUE TITLE
set NEWLINE as delimiter

### ISSUE THREAD

**Issue by payamka** [StevenDevooght/tinyMCE-mention#43]
Hi
Thank you for this great plugin.

I have a question. How I can set NEWLINE as a delimiter then lookup run in new line after typing any thing?

Thank you!

**Comment by StevenDevooght** [comment]
Hi,

I'am afraid that is not possible since tinyMCE converts line breaks to <p></p> tags...

Is there an other character you can use to solve your problem?

**Comment by payamka** [comment]
Thank you for your answer.
I want to run lookup after typing any character and stops after space char. Is it possible?

**Comment by StevenDevooght** [comment]
Start lookup after any character can be done in theory if you configure any character in de delimiter array.  (https://github.com/StevenDevooght/tinyMCE-mention#array-1).

Stopping after space is not possible at the moment. you have to select a value from the dropdown using the mouse or hitting the enter button.
