### ISSUE TITLE
Issue in the first position of the line.

### ISSUE THREAD

**Issue by ssoju** [StevenDevooght/tinyMCE-mention#48]
Look at the follow video.

https://github.com/ssoju/javascript/blob/master/screencast%202016-11-01%2020-18-24.mp4?raw=true

please help me.

**Comment by StevenDevooght** [comment]
Hi,

Can you create a fiddle ([http://fiddle.tinymce.com/](http://fiddle.tinymce.com/)) demonstrating the issue?
