### ISSUE TITLE
"NOTE: Use v3.x if you're using tinyMCE v3.5.x, use v4.x if you're using tinyMCE v4.x"

### ISSUE THREAD

**Issue by NathanWailes** [StevenDevooght/tinyMCE-mention#49]
What is this line from the readme referring to:

> NOTE: Use v3.x if you're using tinyMCE v3.5.x, use v4.x if you're using tinyMCE v4.x

As far as I can tell, there is no jQuery v4.x, and so it seems that line is not referring to versions of jQuery. I'm not sure what else it might be referring to.

**Comment by StevenDevooght** [comment]
Hi, the note is regarding the tinyMCE version.
