### ISSUE TITLE
Onclick button delimiter not registered

### ISSUE THREAD

**Issue by Flatlinezor** [StevenDevooght/tinyMCE-mention#51]
Hello!

Is there a way to get the delimiter registered via a button click?

@ does not seem to trigger mentions although if I were to manually enter it, it works like charm.

onclick: function () {
					
						tinymce.activeEditor.execCommand('mceInsertContent', false, "@");
									}
						});

**Comment by StevenDevooght** [comment]
I don't really understand the question. You want to get the configured delimiter from the mention plugin?

**Comment by Flatlinezor** [comment]
No :) I have two delimiters # and @ configured properly and they work
flawlessly. What I wish to do is having a button on the toolbar for each,
which I have done but since i guess editor.insertcontent is not listened to
by mentions because it does not have onkeyup or onkeydown? Meaning the
delimiters appear in the aditor after pressing the button(s) but they dont
start to engage with mentions as ut normally would. What Am I missing?

**Comment by StevenDevooght** [comment]
Ah, ok

Indeed that functionality is not build in at the moment. I think it should be possible to trigger a keyup event in the button click handler. This should trigger the plugin. Of course it would be nice if we could put this behavior in the plugin itself.

**Comment by Flatlinezor** [comment]
Unforrunately I am afraid I am not good enough to commit that in. If you
ever get time, please try to look into it,maybe it is not thqt time
consuming

**Comment by StevenDevooght** [comment]
What you can do in your button callback is fire the keyup events instead of calling the `insertContent` command.

See example [here](https://github.com/StevenDevooght/tinyMCE-mention/blob/master/tests/test_mention.js#L13).

You can find the keycodes for your delimiters [here](http://web.archive.org/web/20110807175224/http://www.meelink.com/webboard/data/3/0097-1.html).

**Comment by Flatlinezor** [comment]
Thanks for the help. Eventually I will need to use something that guarantees me that the delimiters will be placed in the proper editor (since I will have multiple editors on my page because all the text that I am allowing to be edited are presented as section per section.)

Your example lines will be a good addon for the full plugin since the test one you use is considerably smaller than your full fledged plugin.

**Comment by Flatlinezor** [comment]
Well yes I suck, could not do it after all :) Will wait I guess until it might get implemented ^_^

**Comment by kalati** [comment]
@StevenDevooght  man its not workingin my case in angular4

**Comment by kalati** [comment]
please help me i have same issue and i m trying it from previous 4 days and i have nothing to write in my jira story for time logging 😢
