### ISSUE TITLE
Possible to have two properties to search in for queryBy?

### ISSUE THREAD

**Issue by bkmorse** [StevenDevooght/tinyMCE-mention#53]
Source format:

```
source: [
    { name: 'Tyra Porcelli',  username: 'tyra102' }, 
    { name: 'Brigid Reddish', username: 'brigidx430' },
    { name: 'Ashely Buckler', username: 'sk8ergurl' },
    { name: 'Teddy Whelan', username: 'teddy123' }
]
```

Is it possible to allow for it to search in both the name and username of the source as seen above?

I tried: `queryBy: 'name, username' `and it does not seem like it supports it. Is there any chance it could support that? I would only need the name or username to be inserted after the user selected

**Comment by StevenDevooght** [comment]
You can use the `source` [function](https://github.com/StevenDevooght/tinyMCE-mention#function) and implement your own query logic.
