### ISSUE TITLE
How to auto select the first item in dropdown menu?

### ISSUE THREAD

**Issue by knd** [StevenDevooght/tinyMCE-mention#55]
When the dropdown menu is open, I want the first item in the list to be auto active and be actually selected upon enter key. Similar to the default and then hit down arrow key. 

<img width="526" alt="screen shot 2017-02-13 at 7 12 03 pm" src="https://cloud.githubusercontent.com/assets/1356620/22883009/982a0b1e-f220-11e6-8cfd-94cc992f087e.png">

**Comment by StevenDevooght** [comment]
Hi,

That behavior is currently not supported, but it should be pretty straightforward to build this in.
