### ISSUE TITLE
autocomplete drop down possition in IE & FF off

### ISSUE THREAD

**Issue by chewymole** [StevenDevooght/tinyMCE-mention#59]
new here, not sure how to replicate this, but using latest tinymce and loading the mention with plugins and ajax source with insert callback.

In IE and FF latest, the drop down is off the screen but works correctly in Chrome

**Comment by StevenDevooght** [comment]
Hi,

Are you using version 4.6.4?

The [demo page](http://stevendevooght.github.io/tinyMCE-mention/) is using 4.6.2 and seems to work on all browsers...

**Comment by chewymole** [comment]
Was 4.5.6, then i updated tiny to 4.6.4 and now it works as expected in FF and in Chrome, just not in IE.

In IE11 the drop down shows up below the bottom of the editor. Not a big deal just wondering if there is something i can do to address it.

Thanks again, this is a very nice plugin

**Comment by StevenDevooght** [comment]
Does it work on the demo page? I don't have the issue on my machine in IE...

![image](https://user-images.githubusercontent.com/449346/27675074-c48d9a5c-5ca8-11e7-8f80-1f18299fed1f.png)

**Comment by chewymole** [comment]
Hmm, it does work correctly in the demo. It must be some css forcing it down. 
Thank you

**Comment by chewymole** [comment]
My tiny editor is initialized hidden, and i think that is what is causing the issue. Is there a function i can call to re-compute the position?
