### ISSUE TITLE
autoCompleteData is undefined

### ISSUE THREAD

**Issue by ProdigyView** [StevenDevooght/tinyMCE-mention#69]
I am getting this error when trying to initative the plugin:

> autoCompleteData is undefined

On plugin.js:382:13, which is thie line:

```
// If the delimiter is undefined set default value to ['@'].
            // If the delimiter is a string value convert it to an array. (backwards compatibility)
            autoCompleteData.delimiter = (autoCompleteData.delimiter !== undefined) ? !$.isArray(autoCompleteData.delimiter) ? [autoCompleteData.delimiter] : autoCompleteData.delimiter : ['@'];
```
I am using TinyMCE 4.7.9 and JQuery 3.2.1.

**Comment by StevenDevooght** [comment]
Hi,

Can you create a [fiddle](http://fiddle.tinymce.com/) reproducing the issue?

**Comment by ProdigyView** [comment]
Closing, I just set some options in the wrong place.
