### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by ciricbgd** [StevenDevooght/tinyMCE-mention#87]
Build doesn't pass on version 4.0.1.
Incorporating this into my project yields no errors, but doesn't do anything when  typing the @ symbol

**Comment by StevenDevooght** [comment]
Hi,

The plugin is not actively maintained anymore. You can find a working demo using TinyMCE version 4.6.4 [here](http://stevendevooght.github.io/tinyMCE-mention/).
